// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: src/main/java/Analizador/Lexer.flex
package Analizador;

import java_cup.runtime.Symbol;

// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
public class Lexer implements java_cup.runtime.Scanner {

    /**
     * This character denotes the end of file.
     */
    public static final int YYEOF = -1;

    /**
     * Initial size of the lookahead buffer.
     */
    private static final int ZZ_BUFFERSIZE = 16384;

    // Lexical states.
    public static final int YYINITIAL = 0;
    public static final int STRING = 2;
    public static final int CHAR = 4;
    public static final int COMMENT_L = 6;
    public static final int COMMENT_M = 8;
    public static final int SALTO = 10;

    /**
     * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
     * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l at the
     * beginning of a line l is of the form l = 2*k, k a non negative integer
     */
    private static final int ZZ_LEXSTATE[] = {
        0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5
    };

    /**
     * Top-level table for translating characters to character classes
     */
    private static final int[] ZZ_CMAP_TOP = zzUnpackcmap_top();

    private static final String ZZ_CMAP_TOP_PACKED_0
            = "\1\0\u10ff\u0100";

    private static int[] zzUnpackcmap_top() {
        int[] result = new int[4352];
        int offset = 0;
        offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
        return result;
    }

    private static int zzUnpackcmap_top(String packed, int offset, int[] result) {
        int i = 0;
        /* index in packed string  */
        int j = offset;
        /* index in unpacked array */
        int l = packed.length();
        while (i < l) {
            int count = packed.charAt(i++);
            int value = packed.charAt(i++);
            do {
                result[j++] = value;
            } while (--count > 0);
        }
        return j;
    }

    /**
     * Second-level tables for translating characters to character classes
     */
    private static final int[] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

    private static final String ZZ_CMAP_BLOCKS_PACKED_0
            = "\11\0\1\1\1\2\2\0\1\3\22\0\1\4\1\5"
            + "\1\6\1\7\1\0\1\10\1\11\1\12\1\13\1\14"
            + "\1\15\1\16\1\17\1\20\1\21\1\22\12\23\1\24"
            + "\1\0\1\25\1\26\1\27\1\30\1\0\1\31\1\32"
            + "\1\33\1\34\1\35\1\36\1\37\1\40\1\41\1\42"
            + "\1\43\1\44\1\45\1\46\1\47\1\50\1\51\1\52"
            + "\1\53\1\54\1\55\1\56\1\57\1\60\1\51\1\61"
            + "\1\62\1\63\1\64\1\65\2\51\1\66\1\67\1\70"
            + "\1\71\1\72\1\73\1\74\1\75\1\76\1\77\1\100"
            + "\1\101\1\102\1\103\1\104\1\105\1\51\1\106\1\107"
            + "\1\110\1\111\1\112\1\113\1\114\1\51\1\115\1\116"
            + "\1\117\1\120\101\0\1\121\2\0\1\122\u013d\0";

    private static int[] zzUnpackcmap_blocks() {
        int[] result = new int[512];
        int offset = 0;
        offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
        return result;
    }

    private static int zzUnpackcmap_blocks(String packed, int offset, int[] result) {
        int i = 0;
        /* index in packed string  */
        int j = offset;
        /* index in unpacked array */
        int l = packed.length();
        while (i < l) {
            int count = packed.charAt(i++);
            int value = packed.charAt(i++);
            do {
                result[j++] = value;
            } while (--count > 0);
        }
        return j;
    }

    /**
     * Translates DFA states to action switch labels.
     */
    private static final int[] ZZ_ACTION = zzUnpackAction();

    private static final String ZZ_ACTION_PACKED_0
            = "\5\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7"
            + "\1\10\1\2\1\11\1\12\1\13\1\14\1\15\1\16"
            + "\1\17\1\20\1\21\1\22\1\23\1\24\1\25\22\26"
            + "\1\27\1\30\1\31\21\26\1\32\1\2\1\33\1\34"
            + "\1\35\1\2\1\36\1\37\1\36\1\40\1\36\3\41"
            + "\1\2\1\42\1\1\2\42\1\43\1\0\1\44\1\0"
            + "\1\45\1\46\1\47\1\50\1\51\1\0\1\52\1\53"
            + "\1\54\1\55\1\56\53\26\1\57\3\26\1\57\10\26"
            + "\5\60\1\26\1\61\1\62\1\63\1\64\1\65\1\66"
            + "\1\67\1\70\1\71\1\72\1\73\1\74\1\75\1\76"
            + "\1\77\1\100\74\26\1\101\2\26\1\60\6\26\1\102"
            + "\26\26\1\103\10\26\1\104\13\26\1\105\5\26\1\106"
            + "\16\26\1\107\10\26\1\110\1\111\12\26\1\112\1\113"
            + "\6\26\1\114\12\26\1\115\10\26\1\116\25\26\1\117"
            + "\5\26\1\120\4\26\1\121\2\26\1\122\2\26\1\123"
            + "\2\26\1\124\2\26\1\125\3\26\1\126\7\26\1\127"
            + "\4\26\1\130\1\131\1\132\12\26\1\133\2\26\1\134"
            + "\2\26\1\135\1\136\2\26\1\137\1\140";

    private static int[] zzUnpackAction() {
        int[] result = new int[448];
        int offset = 0;
        offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
        return result;
    }

    private static int zzUnpackAction(String packed, int offset, int[] result) {
        int i = 0;
        /* index in packed string  */
        int j = offset;
        /* index in unpacked array */
        int l = packed.length();
        while (i < l) {
            int count = packed.charAt(i++);
            int value = packed.charAt(i++);
            do {
                result[j++] = value;
            } while (--count > 0);
        }
        return j;
    }

    /**
     * Translates a state to a row index in the transition table
     */
    private static final int[] ZZ_ROWMAP = zzUnpackRowMap();

    private static final String ZZ_ROWMAP_PACKED_0
            = "\0\0\0\123\0\246\0\371\0\u014c\0\u019f\0\u01f2\0\u0245"
            + "\0\u0298\0\u02eb\0\u033e\0\u01f2\0\u01f2\0\u0391\0\u01f2\0\u01f2"
            + "\0\u01f2\0\u01f2\0\u03e4\0\u01f2\0\u0437\0\u01f2\0\u048a\0\u01f2"
            + "\0\u04dd\0\u0530\0\u0583\0\u05d6\0\u0629\0\u067c\0\u06cf\0\u0722"
            + "\0\u0775\0\u07c8\0\u081b\0\u086e\0\u08c1\0\u0914\0\u0967\0\u09ba"
            + "\0\u0a0d\0\u0a60\0\u0ab3\0\u0b06\0\u0b59\0\u07c8\0\u07c8\0\u07c8"
            + "\0\u0bac\0\u0bff\0\u0c52\0\u0ca5\0\u0cf8\0\u0d4b\0\u0d9e\0\u0df1"
            + "\0\u0e44\0\u0e97\0\u0eea\0\u0f3d\0\u0f90\0\u0fe3\0\u1036\0\u1089"
            + "\0\u10dc\0\u01f2\0\u112f\0\u01f2\0\u1182\0\u01f2\0\u11d5\0\u1228"
            + "\0\u1228\0\u127b\0\u01f2\0\u12ce\0\u01f2\0\u0298\0\u02eb\0\u1321"
            + "\0\u01f2\0\u1374\0\u0298\0\u02eb\0\u01f2\0\u13c7\0\u01f2\0\u141a"
            + "\0\u01f2\0\u01f2\0\u01f2\0\u01f2\0\u01f2\0\u146d\0\u01f2\0\u01f2"
            + "\0\u01f2\0\u01f2\0\u01f2\0\u14c0\0\u1513\0\u1566\0\u15b9\0\u160c"
            + "\0\u165f\0\u16b2\0\u1705\0\u1758\0\u17ab\0\u17fe\0\u1851\0\u18a4"
            + "\0\u18f7\0\u194a\0\u199d\0\u19f0\0\u1a43\0\u1a96\0\u1ae9\0\u1b3c"
            + "\0\u1b8f\0\u1be2\0\u1c35\0\u1c88\0\u1cdb\0\u1d2e\0\u1d81\0\u1dd4"
            + "\0\u1e27\0\u1e7a\0\u1ecd\0\u1f20\0\u1f73\0\u1fc6\0\u2019\0\u206c"
            + "\0\u20bf\0\u2112\0\u2165\0\u21b8\0\u220b\0\u225e\0\u22b1\0\u2304"
            + "\0\u2357\0\u23aa\0\u23fd\0\u2450\0\u24a3\0\u24f6\0\u2549\0\u259c"
            + "\0\u25ef\0\u2642\0\u2695\0\u26e8\0\u273b\0\u278e\0\u27e1\0\u2834"
            + "\0\u2887\0\u01f2\0\u01f2\0\u01f2\0\u01f2\0\u01f2\0\u01f2\0\u01f2"
            + "\0\u1228\0\u01f2\0\u1228\0\u1228\0\u1228\0\u1228\0\u01f2\0\u01f2"
            + "\0\u146d\0\u28da\0\u292d\0\u2980\0\u29d3\0\u2a26\0\u2a79\0\u2acc"
            + "\0\u2b1f\0\u2b72\0\u2bc5\0\u2c18\0\u2c6b\0\u2cbe\0\u2d11\0\u2d64"
            + "\0\u2db7\0\u2e0a\0\u2e5d\0\u2eb0\0\u2f03\0\u2f56\0\u2fa9\0\u2ffc"
            + "\0\u304f\0\u30a2\0\u30f5\0\u3148\0\u319b\0\u31ee\0\u3241\0\u3294"
            + "\0\u32e7\0\u333a\0\u338d\0\u33e0\0\u3433\0\u3486\0\u34d9\0\u352c"
            + "\0\u357f\0\u35d2\0\u3625\0\u3678\0\u36cb\0\u371e\0\u3771\0\u37c4"
            + "\0\u3817\0\u386a\0\u38bd\0\u3910\0\u3963\0\u39b6\0\u3a09\0\u3a5c"
            + "\0\u3aaf\0\u3b02\0\u3b55\0\u3ba8\0\u3bfb\0\u07c8\0\u3c4e\0\u3ca1"
            + "\0\u01f2\0\u3cf4\0\u3d47\0\u3d9a\0\u3ded\0\u3e40\0\u3e93\0\u07c8"
            + "\0\u3ee6\0\u3f39\0\u3f8c\0\u3fdf\0\u4032\0\u4085\0\u40d8\0\u412b"
            + "\0\u417e\0\u41d1\0\u4224\0\u4277\0\u42ca\0\u431d\0\u4370\0\u43c3"
            + "\0\u4416\0\u4469\0\u44bc\0\u450f\0\u4562\0\u45b5\0\u07c8\0\u4608"
            + "\0\u465b\0\u46ae\0\u4701\0\u4754\0\u47a7\0\u47fa\0\u484d\0\u07c8"
            + "\0\u48a0\0\u48f3\0\u4946\0\u4999\0\u49ec\0\u4a3f\0\u4a92\0\u4ae5"
            + "\0\u4b38\0\u4b8b\0\u4bde\0\u07c8\0\u4c31\0\u4c84\0\u4cd7\0\u4d2a"
            + "\0\u4d7d\0\u07c8\0\u4dd0\0\u4e23\0\u4e76\0\u4ec9\0\u4f1c\0\u4f6f"
            + "\0\u4fc2\0\u5015\0\u5068\0\u50bb\0\u510e\0\u5161\0\u51b4\0\u5207"
            + "\0\u07c8\0\u525a\0\u52ad\0\u5300\0\u5353\0\u53a6\0\u53f9\0\u544c"
            + "\0\u549f\0\u07c8\0\u07c8\0\u54f2\0\u5545\0\u5598\0\u55eb\0\u563e"
            + "\0\u5691\0\u56e4\0\u5737\0\u578a\0\u57dd\0\u07c8\0\u07c8\0\u5830"
            + "\0\u5883\0\u58d6\0\u5929\0\u597c\0\u59cf\0\u07c8\0\u5a22\0\u5a75"
            + "\0\u5ac8\0\u5b1b\0\u5b6e\0\u5bc1\0\u5c14\0\u5c67\0\u5cba\0\u5d0d"
            + "\0\u07c8\0\u5d60\0\u5db3\0\u5e06\0\u5e59\0\u5eac\0\u5eff\0\u5f52"
            + "\0\u5fa5\0\u07c8\0\u5ff8\0\u604b\0\u609e\0\u60f1\0\u6144\0\u6197"
            + "\0\u61ea\0\u623d\0\u6290\0\u62e3\0\u6336\0\u6389\0\u63dc\0\u642f"
            + "\0\u6482\0\u64d5\0\u6528\0\u657b\0\u65ce\0\u6621\0\u6674\0\u07c8"
            + "\0\u66c7\0\u671a\0\u676d\0\u67c0\0\u6813\0\u07c8\0\u6866\0\u68b9"
            + "\0\u690c\0\u695f\0\u07c8\0\u69b2\0\u6a05\0\u07c8\0\u6a58\0\u6aab"
            + "\0\u07c8\0\u6afe\0\u6b51\0\u07c8\0\u6ba4\0\u6bf7\0\u07c8\0\u6c4a"
            + "\0\u6c9d\0\u6cf0\0\u07c8\0\u6d43\0\u6d96\0\u6de9\0\u6e3c\0\u6e8f"
            + "\0\u6ee2\0\u6f35\0\u07c8\0\u6f88\0\u6fdb\0\u702e\0\u7081\0\u07c8"
            + "\0\u07c8\0\u07c8\0\u70d4\0\u7127\0\u717a\0\u71cd\0\u7220\0\u7273"
            + "\0\u72c6\0\u7319\0\u736c\0\u73bf\0\u07c8\0\u7412\0\u7465\0\u07c8"
            + "\0\u74b8\0\u750b\0\u07c8\0\u07c8\0\u755e\0\u75b1\0\u07c8\0\u07c8";

    private static int[] zzUnpackRowMap() {
        int[] result = new int[448];
        int offset = 0;
        offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
        return result;
    }

    private static int zzUnpackRowMap(String packed, int offset, int[] result) {
        int i = 0;
        /* index in packed string  */
        int j = offset;
        /* index in unpacked array */
        int l = packed.length();
        while (i < l) {
            int high = packed.charAt(i++) << 16;
            result[j++] = high | packed.charAt(i++);
        }
        return j;
    }

    /**
     * The transition table of the DFA
     */
    private static final int[] ZZ_TRANS = zzUnpackTrans();

    private static final String ZZ_TRANS_PACKED_0
            = "\2\7\1\10\1\11\1\12\1\13\1\14\1\7\1\15"
            + "\1\16\1\17\1\20\1\21\1\22\1\23\1\24\1\25"
            + "\1\7\1\26\1\27\1\30\1\31\1\32\1\33\1\7"
            + "\1\34\1\35\1\36\1\37\1\40\1\41\1\42\1\43"
            + "\1\44\1\42\1\45\1\46\1\47\1\42\1\50\1\51"
            + "\1\42\1\52\1\53\1\54\1\42\1\55\3\42\1\56"
            + "\1\42\1\57\1\60\1\61\1\62\1\63\1\64\1\65"
            + "\1\66\1\42\1\67\1\70\1\42\1\71\1\72\1\73"
            + "\1\42\1\74\1\75\1\76\1\77\1\100\1\42\1\101"
            + "\3\42\1\102\1\103\1\104\2\7\6\105\1\106\1\107"
            + "\73\105\1\7\2\105\1\7\1\105\1\7\12\105\5\110"
            + "\1\111\1\110\1\112\2\111\1\113\2\111\4\110\1\111"
            + "\1\110\1\111\4\110\66\111\4\110\1\114\2\115\1\113"
            + "\1\116\1\117\121\115\1\116\1\117\13\115\1\120\6\115"
            + "\1\7\73\115\1\121\1\122\1\121\1\123\1\124\116\121"
            + "\125\0\1\10\123\0\1\11\123\0\1\12\123\0\1\125"
            + "\3\0\1\126\14\0\1\127\70\0\1\130\14\0\1\131"
            + "\105\0\1\132\21\0\1\133\7\0\1\134\114\0\1\135"
            + "\123\0\1\136\1\0\1\27\117\0\1\137\4\0\1\140"
            + "\1\141\122\0\1\142\122\0\1\143\117\0\1\42\5\0"
            + "\22\42\1\144\33\42\1\145\6\42\30\0\1\42\5\0"
            + "\16\42\1\146\34\42\1\147\11\42\30\0\1\42\5\0"
            + "\1\150\15\42\1\151\16\42\1\152\15\42\1\153\11\42"
            + "\30\0\1\42\5\0\4\42\1\154\11\42\1\155\22\42"
            + "\1\156\11\42\1\157\11\42\30\0\1\42\5\0\15\42"
            + "\1\160\4\42\1\161\4\42\1\162\22\42\1\163\3\42"
            + "\1\164\4\42\1\165\1\42\30\0\1\42\5\0\1\166"
            + "\34\42\1\167\27\42\30\0\1\42\5\0\65\42\30\0"
            + "\1\42\5\0\1\170\34\42\1\171\27\42\30\0\1\42"
            + "\5\0\14\42\1\172\34\42\1\173\13\42\30\0\1\42"
            + "\5\0\4\42\1\174\34\42\1\175\23\42\30\0\1\42"
            + "\5\0\16\42\1\176\34\42\1\177\11\42\30\0\1\42"
            + "\5\0\4\42\1\200\3\42\1\201\30\42\1\202\3\42"
            + "\1\203\17\42\30\0\1\42\5\0\21\42\1\204\33\42"
            + "\1\205\7\42\30\0\1\42\5\0\1\206\7\42\1\207"
            + "\10\42\1\210\13\42\1\211\7\42\1\212\7\42\1\213"
            + "\7\42\30\0\1\42\5\0\4\42\1\214\34\42\1\215"
            + "\23\42\30\0\1\42\5\0\1\216\7\42\1\217\13\42"
            + "\1\220\1\42\1\221\6\42\1\222\7\42\1\223\12\42"
            + "\1\224\1\42\1\225\2\42\30\0\1\42\5\0\21\42"
            + "\1\226\33\42\1\227\7\42\30\0\1\42\5\0\1\230"
            + "\3\42\1\231\30\42\1\232\3\42\1\233\23\42\30\0"
            + "\1\42\5\0\56\42\1\145\6\42\30\0\1\42\5\0"
            + "\53\42\1\147\11\42\30\0\1\42\5\0\35\42\1\152"
            + "\15\42\1\153\11\42\30\0\1\42\5\0\41\42\1\156"
            + "\11\42\1\234\11\42\30\0\1\42\5\0\52\42\1\163"
            + "\3\42\1\164\4\42\1\165\1\42\30\0\1\42\5\0"
            + "\35\42\1\235\27\42\30\0\1\42\5\0\35\42\1\171"
            + "\27\42\30\0\1\42\5\0\51\42\1\173\13\42\30\0"
            + "\1\42\5\0\41\42\1\175\23\42\30\0\1\42\5\0"
            + "\35\42\1\236\15\42\1\177\11\42\30\0\1\42\5\0"
            + "\41\42\1\202\3\42\1\237\17\42\30\0\1\42\5\0"
            + "\55\42\1\205\7\42\30\0\1\42\5\0\35\42\1\211"
            + "\7\42\1\212\7\42\1\213\7\42\30\0\1\42\5\0"
            + "\41\42\1\240\23\42\30\0\1\42\5\0\35\42\1\222"
            + "\7\42\1\223\5\42\1\241\4\42\1\224\1\42\1\225"
            + "\2\42\30\0\1\42\5\0\55\42\1\227\7\42\30\0"
            + "\1\42\5\0\35\42\1\232\3\42\1\233\23\42\124\0"
            + "\1\242\3\0\6\105\2\0\73\105\1\0\2\105\1\0"
            + "\1\105\1\0\12\105\6\0\1\243\1\244\53\0\1\245"
            + "\17\0\1\246\2\0\1\247\1\0\1\250\12\0\12\110"
            + "\1\0\117\110\1\251\2\110\1\252\50\110\1\253\17\110"
            + "\1\254\2\110\1\255\1\110\1\256\24\110\1\0\106\110"
            + "\1\111\1\110\27\0\1\113\74\0\1\122\132\0\1\257"
            + "\230\0\1\260\26\0\1\261\122\0\1\42\5\0\2\42"
            + "\1\262\62\42\30\0\1\42\5\0\37\42\1\263\25\42"
            + "\30\0\1\42\5\0\16\42\1\264\46\42\30\0\1\42"
            + "\5\0\53\42\1\265\11\42\30\0\1\42\5\0\3\42"
            + "\1\266\15\42\1\267\1\270\42\42\30\0\1\42\5\0"
            + "\15\42\1\271\47\42\30\0\1\42\5\0\40\42\1\272"
            + "\14\42\1\273\1\274\6\42\30\0\1\42\5\0\52\42"
            + "\1\275\12\42\30\0\1\42\5\0\5\42\1\276\14\42"
            + "\1\277\42\42\30\0\1\42\5\0\1\42\1\300\63\42"
            + "\30\0\1\42\5\0\42\42\1\301\13\42\1\302\6\42"
            + "\30\0\1\42\5\0\36\42\1\303\26\42\30\0\1\42"
            + "\5\0\23\42\1\304\41\42\30\0\1\42\5\0\17\42"
            + "\1\305\45\42\30\0\1\42\5\0\23\42\1\306\41\42"
            + "\30\0\1\42\5\0\57\42\1\307\5\42\30\0\1\42"
            + "\5\0\54\42\1\310\10\42\30\0\1\42\5\0\57\42"
            + "\1\311\5\42\30\0\1\42\5\0\13\42\1\312\51\42"
            + "\30\0\1\42\5\0\50\42\1\313\14\42\30\0\1\42"
            + "\5\0\2\42\1\314\62\42\30\0\1\42\5\0\37\42"
            + "\1\315\25\42\30\0\1\42\5\0\17\42\1\316\45\42"
            + "\30\0\1\42\5\0\54\42\1\317\10\42\30\0\1\42"
            + "\5\0\4\42\1\320\60\42\30\0\1\42\5\0\41\42"
            + "\1\321\23\42\30\0\1\42\5\0\15\42\1\322\47\42"
            + "\30\0\1\42\5\0\52\42\1\323\12\42\30\0\1\42"
            + "\5\0\15\42\1\324\47\42\30\0\1\42\5\0\4\42"
            + "\1\325\60\42\30\0\1\42\5\0\52\42\1\326\12\42"
            + "\30\0\1\42\5\0\41\42\1\327\23\42\30\0\1\42"
            + "\5\0\3\42\1\330\61\42\30\0\1\42\5\0\40\42"
            + "\1\331\24\42\30\0\1\42\5\0\21\42\1\332\43\42"
            + "\30\0\1\42\5\0\22\42\1\333\42\42\30\0\1\42"
            + "\5\0\10\42\1\334\54\42\30\0\1\42\5\0\55\42"
            + "\1\335\7\42\30\0\1\42\5\0\56\42\1\336\6\42"
            + "\30\0\1\42\5\0\45\42\1\337\17\42\30\0\1\42"
            + "\5\0\17\42\1\340\3\42\1\341\41\42\30\0\1\42"
            + "\5\0\54\42\1\342\2\42\1\343\5\42\30\0\1\42"
            + "\5\0\13\42\1\344\51\42\30\0\1\42\5\0\15\42"
            + "\1\345\47\42\30\0\1\42\5\0\14\42\1\346\50\42"
            + "\30\0\1\42\5\0\10\42\1\347\54\42\30\0\1\42"
            + "\5\0\50\42\1\350\14\42\30\0\1\42\5\0\52\42"
            + "\1\351\12\42\30\0\1\42\5\0\51\42\1\352\13\42"
            + "\30\0\1\42\5\0\45\42\1\353\17\42\30\0\1\42"
            + "\5\0\24\42\1\354\40\42\30\0\1\42\5\0\60\42"
            + "\1\355\4\42\30\0\1\42\5\0\21\42\1\356\43\42"
            + "\30\0\1\42\5\0\21\42\1\357\43\42\30\0\1\42"
            + "\5\0\55\42\1\356\7\42\30\0\1\42\5\0\55\42"
            + "\1\360\7\42\14\0\1\361\13\0\1\42\5\0\36\42"
            + "\1\303\26\42\14\0\1\361\13\0\1\42\5\0\50\42"
            + "\1\313\14\42\14\0\1\361\13\0\1\42\5\0\65\42"
            + "\14\0\1\361\13\0\1\42\5\0\41\42\1\327\23\42"
            + "\14\0\1\361\13\0\1\42\5\0\54\42\1\342\2\42"
            + "\1\343\5\42\30\0\1\42\5\0\50\42\1\236\14\42"
            + "\30\0\1\42\5\0\4\42\1\362\60\42\30\0\1\42"
            + "\5\0\41\42\1\363\23\42\30\0\1\42\5\0\13\42"
            + "\1\364\51\42\30\0\1\42\5\0\50\42\1\365\14\42"
            + "\30\0\1\42\5\0\4\42\1\366\60\42\30\0\1\42"
            + "\5\0\1\367\64\42\30\0\1\42\5\0\16\42\1\370"
            + "\46\42\30\0\1\42\5\0\23\42\1\371\41\42\30\0"
            + "\1\42\5\0\41\42\1\372\23\42\30\0\1\42\5\0"
            + "\35\42\1\373\27\42\30\0\1\42\5\0\53\42\1\370"
            + "\11\42\30\0\1\42\5\0\57\42\1\374\5\42\30\0"
            + "\1\42\5\0\1\375\64\42\30\0\1\42\5\0\2\42"
            + "\1\376\62\42\30\0\1\42\5\0\13\42\1\377\51\42"
            + "\30\0\1\42\5\0\35\42\1\u0100\27\42\30\0\1\42"
            + "\5\0\37\42\1\u0101\25\42\30\0\1\42\5\0\50\42"
            + "\1\u0102\14\42\30\0\1\42\5\0\4\42\1\u0103\60\42"
            + "\30\0\1\42\5\0\4\42\1\u0104\60\42\30\0\1\42"
            + "\5\0\10\42\1\u0105\54\42\30\0\1\42\5\0\41\42"
            + "\1\u0106\23\42\30\0\1\42\5\0\41\42\1\u0107\23\42"
            + "\30\0\1\42\5\0\45\42\1\u0108\17\42\30\0\1\42"
            + "\5\0\22\42\1\u0109\42\42\30\0\1\42\5\0\56\42"
            + "\1\u010a\6\42\30\0\1\42\5\0\4\42\1\u010b\60\42"
            + "\30\0\1\42\5\0\41\42\1\u010c\23\42\30\0\1\42"
            + "\5\0\1\u010d\64\42\30\0\1\42\5\0\35\42\1\u010e"
            + "\27\42\30\0\1\42\5\0\17\42\1\u010f\45\42\30\0"
            + "\1\42\5\0\54\42\1\u010f\10\42\30\0\1\42\5\0"
            + "\6\42\1\u0110\56\42\30\0\1\42\5\0\43\42\1\u0111"
            + "\21\42\30\0\1\42\5\0\22\42\1\u0112\42\42\30\0"
            + "\1\42\5\0\15\42\1\u0113\47\42\30\0\1\42\5\0"
            + "\56\42\1\u0114\6\42\30\0\1\42\5\0\52\42\1\u0115"
            + "\12\42\30\0\1\42\5\0\4\42\1\u0116\60\42\30\0"
            + "\1\42\5\0\41\42\1\u0117\23\42\30\0\1\42\5\0"
            + "\1\u0118\3\42\1\u0119\60\42\30\0\1\42\5\0\23\42"
            + "\1\u011a\41\42\30\0\1\42\5\0\15\42\1\u011b\47\42"
            + "\30\0\1\42\5\0\35\42\1\u0118\3\42\1\u011c\23\42"
            + "\30\0\1\42\5\0\57\42\1\u011d\5\42\30\0\1\42"
            + "\5\0\52\42\1\u011e\12\42\30\0\1\42\5\0\21\42"
            + "\1\u011f\43\42\30\0\1\42\5\0\16\42\1\u0120\46\42"
            + "\30\0\1\42\5\0\55\42\1\u0121\7\42\30\0\1\42"
            + "\5\0\53\42\1\u0122\11\42\30\0\1\42\5\0\10\42"
            + "\1\u0123\54\42\30\0\1\42\5\0\16\42\1\u0124\46\42"
            + "\30\0\1\42\5\0\1\u0125\64\42\30\0\1\42\5\0"
            + "\23\42\1\u0126\41\42\30\0\1\42\5\0\45\42\1\u0127"
            + "\17\42\30\0\1\42\5\0\53\42\1\u0124\11\42\30\0"
            + "\1\42\5\0\35\42\1\u0128\27\42\30\0\1\42\5\0"
            + "\57\42\1\u0129\5\42\30\0\1\42\5\0\4\42\1\u012a"
            + "\60\42\30\0\1\42\5\0\41\42\1\u012a\23\42\30\0"
            + "\1\42\5\0\3\42\1\u012b\61\42\30\0\1\42\5\0"
            + "\40\42\1\u012c\24\42\30\0\1\42\5\0\15\42\1\u012d"
            + "\47\42\30\0\1\42\5\0\52\42\1\u012e\12\42\30\0"
            + "\1\42\5\0\4\42\1\u012f\60\42\30\0\1\42\5\0"
            + "\41\42\1\u0130\23\42\30\0\1\42\5\0\15\42\1\u0131"
            + "\47\42\30\0\1\42\5\0\2\42\1\u0132\62\42\30\0"
            + "\1\42\5\0\10\42\1\u0133\54\42\30\0\1\42\5\0"
            + "\52\42\1\u0134\12\42\30\0\1\42\5\0\37\42\1\u0135"
            + "\25\42\30\0\1\42\5\0\45\42\1\u0136\17\42\30\0"
            + "\1\42\5\0\24\42\1\u0137\40\42\30\0\1\42\5\0"
            + "\4\42\1\u0138\60\42\30\0\1\42\5\0\4\42\1\u0139"
            + "\60\42\30\0\1\42\5\0\60\42\1\u013a\4\42\30\0"
            + "\1\42\5\0\41\42\1\u013b\23\42\30\0\1\42\5\0"
            + "\41\42\1\u0139\23\42\30\0\1\42\5\0\21\42\1\u013c"
            + "\43\42\30\0\1\42\5\0\21\42\1\u013d\43\42\30\0"
            + "\1\42\5\0\4\42\1\u013e\60\42\30\0\1\42\5\0"
            + "\55\42\1\u013f\7\42\30\0\1\42\5\0\55\42\1\u0140"
            + "\7\42\30\0\1\42\5\0\41\42\1\u0141\23\42\30\0"
            + "\1\42\5\0\4\42\1\u0142\11\42\1\u0142\46\42\30\0"
            + "\1\42\5\0\41\42\1\u0142\11\42\1\u0142\11\42\30\0"
            + "\1\42\5\0\21\42\1\u0143\43\42\30\0\1\42\5\0"
            + "\55\42\1\u0143\7\42\30\0\1\42\5\0\21\42\1\u0144"
            + "\43\42\30\0\1\42\5\0\55\42\1\u0145\7\42\30\0"
            + "\1\42\5\0\10\42\1\u0146\54\42\30\0\1\42\5\0"
            + "\45\42\1\u0147\17\42\30\0\1\42\5\0\1\u0148\64\42"
            + "\30\0\1\42\5\0\23\42\1\u0149\41\42\30\0\1\42"
            + "\5\0\35\42\1\u014a\27\42\30\0\1\42\5\0\57\42"
            + "\1\u014b\5\42\30\0\1\42\5\0\15\42\1\u014c\47\42"
            + "\30\0\1\42\5\0\52\42\1\u014d\12\42\30\0\1\42"
            + "\5\0\22\42\1\u014e\42\42\30\0\1\42\5\0\1\u014f"
            + "\64\42\30\0\1\42\5\0\2\42\1\u0150\62\42\30\0"
            + "\1\42\5\0\56\42\1\u014e\6\42\30\0\1\42\5\0"
            + "\35\42\1\u014f\27\42\30\0\1\42\5\0\37\42\1\u0151"
            + "\25\42\30\0\1\42\5\0\16\42\1\u0152\46\42\30\0"
            + "\1\42\5\0\21\42\1\u0153\43\42\30\0\1\42\5\0"
            + "\53\42\1\u0154\11\42\30\0\1\42\5\0\55\42\1\u0155"
            + "\7\42\30\0\1\42\5\0\21\42\1\u0156\43\42\30\0"
            + "\1\42\5\0\21\42\1\u0157\43\42\30\0\1\42\5\0"
            + "\2\42\1\u0158\62\42\30\0\1\42\5\0\55\42\1\u0156"
            + "\7\42\30\0\1\42\5\0\55\42\1\u0159\7\42\30\0"
            + "\1\42\5\0\37\42\1\u015a\25\42\30\0\1\42\5\0"
            + "\1\u015b\64\42\30\0\1\42\5\0\35\42\1\u015c\27\42"
            + "\30\0\1\42\5\0\3\42\1\u015d\61\42\30\0\1\42"
            + "\5\0\40\42\1\u015e\24\42\30\0\1\42\5\0\1\u015f"
            + "\64\42\30\0\1\42\5\0\35\42\1\u0160\27\42\30\0"
            + "\1\42\5\0\1\u0161\64\42\30\0\1\42\5\0\23\42"
            + "\1\u0162\41\42\30\0\1\42\5\0\15\42\1\u0163\47\42"
            + "\30\0\1\42\5\0\35\42\1\u0161\27\42\30\0\1\42"
            + "\5\0\57\42\1\u0164\5\42\30\0\1\42\5\0\52\42"
            + "\1\u0165\12\42\30\0\1\42\5\0\13\42\1\u0166\51\42"
            + "\30\0\1\42\5\0\15\42\1\u0167\47\42\30\0\1\42"
            + "\5\0\50\42\1\u0168\14\42\30\0\1\42\5\0\52\42"
            + "\1\u0169\12\42\30\0\1\42\5\0\16\42\1\u016a\46\42"
            + "\30\0\1\42\5\0\1\u016b\64\42\30\0\1\42\5\0"
            + "\15\42\1\u016c\47\42\30\0\1\42\5\0\53\42\1\u016a"
            + "\11\42\30\0\1\42\5\0\35\42\1\u016d\27\42\30\0"
            + "\1\42\5\0\52\42\1\u016e\12\42\30\0\1\42\5\0"
            + "\4\42\1\u016f\60\42\30\0\1\42\5\0\41\42\1\u0170"
            + "\23\42\30\0\1\42\5\0\23\42\1\u0171\41\42\30\0"
            + "\1\42\5\0\57\42\1\u0172\5\42\30\0\1\42\5\0"
            + "\11\42\1\u0173\53\42\30\0\1\42\5\0\21\42\1\u0174"
            + "\43\42\30\0\1\42\5\0\46\42\1\u0175\16\42\30\0"
            + "\1\42\5\0\55\42\1\u0176\7\42\30\0\1\42\5\0"
            + "\1\u0177\64\42\30\0\1\42\5\0\35\42\1\u0178\27\42"
            + "\30\0\1\42\5\0\10\42\1\u0179\54\42\30\0\1\42"
            + "\5\0\45\42\1\u017a\17\42\30\0\1\42\5\0\3\42"
            + "\1\u017b\61\42\30\0\1\42\5\0\15\42\1\u017c\47\42"
            + "\30\0\1\42\5\0\40\42\1\u017d\24\42\30\0\1\42"
            + "\5\0\52\42\1\u017e\12\42\30\0\1\42\5\0\10\42"
            + "\1\u017f\54\42\30\0\1\42\5\0\7\42\1\u0180\55\42"
            + "\30\0\1\42\5\0\45\42\1\u0181\17\42\30\0\1\42"
            + "\5\0\44\42\1\u0180\20\42\30\0\1\42\5\0\3\42"
            + "\1\u0182\61\42\30\0\1\42\5\0\40\42\1\u0183\24\42"
            + "\30\0\1\42\5\0\4\42\1\u0184\60\42\30\0\1\42"
            + "\5\0\41\42\1\u0185\23\42\30\0\1\42\5\0\15\42"
            + "\1\u0186\47\42\30\0\1\42\5\0\52\42\1\u0186\12\42"
            + "\30\0\1\42\5\0\4\42\1\u0187\60\42\30\0\1\42"
            + "\5\0\24\42\1\u0188\40\42\30\0\1\42\5\0\41\42"
            + "\1\u0189\23\42\30\0\1\42\5\0\60\42\1\u018a\4\42"
            + "\30\0\1\42\5\0\23\42\1\u018b\41\42\30\0\1\42"
            + "\5\0\3\42\1\u018c\61\42\30\0\1\42\5\0\57\42"
            + "\1\u018b\5\42\30\0\1\42\5\0\40\42\1\u018d\24\42"
            + "\30\0\1\42\5\0\21\42\1\u018e\43\42\30\0\1\42"
            + "\5\0\3\42\1\u018f\61\42\30\0\1\42\5\0\55\42"
            + "\1\u018e\7\42\30\0\1\42\5\0\40\42\1\u0190\24\42"
            + "\30\0\1\42\5\0\22\42\1\u0191\42\42\30\0\1\42"
            + "\5\0\56\42\1\u0191\6\42\30\0\1\42\5\0\24\42"
            + "\1\u0192\40\42\30\0\1\42\5\0\60\42\1\u0193\4\42"
            + "\30\0\1\42\5\0\4\42\1\u0194\60\42\30\0\1\42"
            + "\5\0\1\u0195\64\42\30\0\1\42\5\0\41\42\1\u0194"
            + "\23\42\30\0\1\42\5\0\35\42\1\u0196\27\42\30\0"
            + "\1\42\5\0\21\42\1\u0197\43\42\30\0\1\42\5\0"
            + "\55\42\1\u0197\7\42\30\0\1\42\5\0\17\42\1\u0198"
            + "\45\42\30\0\1\42\5\0\54\42\1\u0199\10\42\30\0"
            + "\1\42\5\0\24\42\1\u019a\40\42\30\0\1\42\5\0"
            + "\1\u019b\64\42\30\0\1\42\5\0\60\42\1\u019c\4\42"
            + "\30\0\1\42\5\0\35\42\1\u019b\27\42\30\0\1\42"
            + "\5\0\30\42\1\u019d\34\42\30\0\1\42\5\0\64\42"
            + "\1\u019e\30\0\1\42\5\0\4\42\1\u019f\60\42\30\0"
            + "\1\42\5\0\41\42\1\u01a0\23\42\30\0\1\42\5\0"
            + "\15\42\1\u01a1\47\42\30\0\1\42\5\0\52\42\1\u01a2"
            + "\12\42\30\0\1\42\5\0\21\42\1\u01a3\43\42\30\0"
            + "\1\42\5\0\1\u01a4\64\42\30\0\1\42\5\0\55\42"
            + "\1\u01a3\7\42\30\0\1\42\5\0\35\42\1\u01a5\27\42"
            + "\30\0\1\42\5\0\4\42\1\u01a6\60\42\30\0\1\42"
            + "\5\0\41\42\1\u01a7\23\42\30\0\1\42\5\0\4\42"
            + "\1\u01a8\60\42\30\0\1\42\5\0\41\42\1\u01a8\23\42"
            + "\30\0\1\42\5\0\3\42\1\u01a9\61\42\30\0\1\42"
            + "\5\0\40\42\1\u01a9\24\42\30\0\1\42\5\0\22\42"
            + "\1\u01aa\42\42\30\0\1\42\5\0\56\42\1\u01aa\6\42"
            + "\30\0\1\42\5\0\1\u01ab\64\42\30\0\1\42\5\0"
            + "\35\42\1\u01ac\27\42\30\0\1\42\5\0\2\42\1\u01ad"
            + "\62\42\30\0\1\42\5\0\37\42\1\u01ae\25\42\30\0"
            + "\1\42\5\0\1\u01af\64\42\30\0\1\42\5\0\35\42"
            + "\1\u01b0\27\42\30\0\1\42\5\0\21\42\1\u01b1\43\42"
            + "\30\0\1\42\5\0\55\42\1\u01b2\7\42\30\0\1\42"
            + "\5\0\23\42\1\u01b3\41\42\30\0\1\42\5\0\57\42"
            + "\1\u01b4\5\42\30\0\1\42\5\0\21\42\1\u01b5\43\42"
            + "\30\0\1\42\5\0\55\42\1\u01b5\7\42\30\0\1\42"
            + "\5\0\15\42\1\u01b6\47\42\30\0\1\42\5\0\52\42"
            + "\1\u01b7\12\42\30\0\1\42\5\0\13\42\1\u01b8\51\42"
            + "\30\0\1\42\5\0\50\42\1\u01b8\14\42\30\0\1\42"
            + "\5\0\10\42\1\u01b9\54\42\30\0\1\42\5\0\45\42"
            + "\1\u01ba\17\42\30\0\1\42\5\0\21\42\1\u01bb\43\42"
            + "\30\0\1\42\5\0\55\42\1\u01bb\7\42\30\0\1\42"
            + "\5\0\16\42\1\u012a\46\42\30\0\1\42\5\0\53\42"
            + "\1\u012a\11\42\30\0\1\42\5\0\4\42\1\u01bc\60\42"
            + "\30\0\1\42\5\0\41\42\1\u01bc\23\42\30\0\1\42"
            + "\5\0\23\42\1\u01bd\41\42\30\0\1\42\5\0\57\42"
            + "\1\u01be\5\42\30\0\1\42\5\0\21\42\1\u01bf\43\42"
            + "\30\0\1\42\5\0\55\42\1\u01bf\7\42\30\0\1\42"
            + "\5\0\4\42\1\u01c0\60\42\30\0\1\42\5\0\41\42"
            + "\1\u01c0\23\42\5\0";

    private static int[] zzUnpackTrans() {
        int[] result = new int[30212];
        int offset = 0;
        offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
        return result;
    }

    private static int zzUnpackTrans(String packed, int offset, int[] result) {
        int i = 0;
        /* index in packed string  */
        int j = offset;
        /* index in unpacked array */
        int l = packed.length();
        while (i < l) {
            int count = packed.charAt(i++);
            int value = packed.charAt(i++);
            value--;
            do {
                result[j++] = value;
            } while (--count > 0);
        }
        return j;
    }

    /**
     * Error code for "Unknown internal scanner error".
     */
    private static final int ZZ_UNKNOWN_ERROR = 0;
    /**
     * Error code for "could not match input".
     */
    private static final int ZZ_NO_MATCH = 1;
    /**
     * Error code for "pushback value was too large".
     */
    private static final int ZZ_PUSHBACK_2BIG = 2;

    /**
     * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
     * {@link #ZZ_PUSHBACK_2BIG} respectively.
     */
    private static final String ZZ_ERROR_MSG[] = {
        "Unknown internal scanner error",
        "Error: could not match input",
        "Error: pushback value was too large"
    };

    /**
     * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
     */
    private static final int[] ZZ_ATTRIBUTE = zzUnpackAttribute();

    private static final String ZZ_ATTRIBUTE_PACKED_0
            = "\5\0\1\1\1\11\4\1\2\11\1\1\4\11\1\1"
            + "\1\11\1\1\1\11\1\1\1\11\51\1\1\11\1\1"
            + "\1\11\1\1\1\11\4\1\1\11\1\1\1\11\3\1"
            + "\1\11\3\1\1\11\1\0\1\11\1\0\5\11\1\0"
            + "\5\11\76\1\7\11\1\1\1\11\4\1\2\11\100\1"
            + "\1\11\317\1";

    private static int[] zzUnpackAttribute() {
        int[] result = new int[448];
        int offset = 0;
        offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
        return result;
    }

    private static int zzUnpackAttribute(String packed, int offset, int[] result) {
        int i = 0;
        /* index in packed string  */
        int j = offset;
        /* index in unpacked array */
        int l = packed.length();
        while (i < l) {
            int count = packed.charAt(i++);
            int value = packed.charAt(i++);
            do {
                result[j++] = value;
            } while (--count > 0);
        }
        return j;
    }

    /**
     * Input device.
     */
    private java.io.Reader zzReader;

    /**
     * Current state of the DFA.
     */
    private int zzState;

    /**
     * Current lexical state.
     */
    private int zzLexicalState = YYINITIAL;

    /**
     * This buffer contains the current text to be matched and is the source of
     * the {@link #yytext()} string.
     */
    private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

    /**
     * Text position at the last accepting state.
     */
    private int zzMarkedPos;

    /**
     * Current text position in the buffer.
     */
    private int zzCurrentPos;

    /**
     * Marks the beginning of the {@link #yytext()} string in the buffer.
     */
    private int zzStartRead;

    /**
     * Marks the last character in the buffer, that has been read from input.
     */
    private int zzEndRead;

    /**
     * Whether the scanner is at the end of file.
     *
     * @see #yyatEOF
     */
    private boolean zzAtEOF;

    /**
     * The number of occupied positions in {@link #zzBuffer} beyond
     * {@link #zzEndRead}.
     *
     * <p>
     * When a lead/high surrogate has been read from the input stream into the
     * final {@link #zzBuffer} position, this will have a value of 1; otherwise,
     * it will have a value of 0.
     */
    private int zzFinalHighSurrogate = 0;

    /**
     * Number of newlines encountered up to the start of the matched text.
     */
    private int yyline;

    /**
     * Number of characters from the last newline up to the start of the matched
     * text.
     */
    private int yycolumn;

    /**
     * Number of characters up to the start of the matched text.
     */
    private long yychar;

    /**
     * Whether the scanner is currently at the beginning of a line.
     */
    @SuppressWarnings("unused")
    private boolean zzAtBOL = true;

    /**
     * Whether the user-EOF-code has already been executed.
     */
    private boolean zzEOFDone;

    /* user code: */
    StringBuffer string = new StringBuffer();
    int indentados = 0;

    private Symbol symbol(int type, Object value) {
        return new Symbol(type, yyline, yycolumn, value);
    }

    private Symbol symbol(int type) {
        return new Symbol(type, yyline, yycolumn, yytext());
    }

    public Symbol indent(String analizar, boolean tieneTab, boolean esEOF) {
        if (!esEOF) {
            if (tieneTab) {
                int espacios = 0;
                for (int i = 0; i < analizar.length(); i++) {
                    if (analizar.charAt(i) == '\t') {
                        espacios++;
                    }
                }
                if ((indentados - espacios) > 0) {
                    indentados--;
                    yypushback(espacios);
                    System.out.println("Se encuentra dedentado no1");
                    return new Symbol(sym.DEDENT, yyline, yycolumn, yytext());
                } else if ((indentados - espacios)==0) {
                    yybegin(YYINITIAL);
                    return null;
                } else if ((indentados - espacios) < 0) {
                    indentados++;
                    yypushback(espacios);
                    System.out.println("Se encuentra indentado");
                    return new Symbol(sym.INDENT, yyline, yycolumn, yytext());
                } else {
                    System.out.println("No sé como entró acá");
                    return null;
                }
            } else {
                if (indentados > 0) {
                    indentados--;
                    yypushback(1);
                    System.out.println("Se encuentra dedentado no2");
                    return new Symbol(sym.DEDENT, yyline, yycolumn, yytext());
                } else {
                    yybegin(YYINITIAL);
                    yypushback(1);
                    return null;
                }
            }
        } else {
            if (indentados > 0) {
                indentados--;
                System.out.println("Se encuentra dedentado no3");
                return new Symbol(sym.DEDENT, yyline, yycolumn, yytext());
            } else {
                return new java_cup.runtime.Symbol(sym.EOF);
            }
        }
    }

    /**
     * Creates a new scanner
     *
     * @param in the java.io.Reader to read input from.
     */
    public Lexer(java.io.Reader in) {
        this.zzReader = in;
    }

    /**
     * Translates raw input code points to DFA table row
     */
    private static int zzCMap(int input) {
        int offset = input & 255;
        return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
    }

    /**
     * Refills the input buffer.
     *
     * @return {@code false} iff there was new input.
     * @exception java.io.IOException if any I/O-Error occurs
     */
    private boolean zzRefill() throws java.io.IOException {

        /* first: make room (if you can) */
        if (zzStartRead > 0) {
            zzEndRead += zzFinalHighSurrogate;
            zzFinalHighSurrogate = 0;
            System.arraycopy(zzBuffer, zzStartRead,
                    zzBuffer, 0,
                    zzEndRead - zzStartRead);

            /* translate stored positions */
            zzEndRead -= zzStartRead;
            zzCurrentPos -= zzStartRead;
            zzMarkedPos -= zzStartRead;
            zzStartRead = 0;
        }

        /* is the buffer big enough? */
        if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
            /* if not: blow it up */
            char newBuffer[] = new char[zzBuffer.length * 2];
            System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
            zzBuffer = newBuffer;
            zzEndRead += zzFinalHighSurrogate;
            zzFinalHighSurrogate = 0;
        }

        /* fill the buffer with new input */
        int requested = zzBuffer.length - zzEndRead;
        int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

        /* not supposed to occur according to specification of java.io.Reader */
        if (numRead == 0) {
            throw new java.io.IOException(
                    "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
        }
        if (numRead > 0) {
            zzEndRead += numRead;
            if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
                if (numRead == requested) { // We requested too few chars to encode a full Unicode character
                    --zzEndRead;
                    zzFinalHighSurrogate = 1;
                } else {                    // There is room in the buffer for at least one more char
                    int c = zzReader.read();  // Expecting to read a paired low surrogate char
                    if (c == -1) {
                        return true;
                    } else {
                        zzBuffer[zzEndRead++] = (char) c;
                    }
                }
            }
            /* potentially more input available */
            return false;
        }

        /* numRead < 0 ==> end of stream */
        return true;
    }

    /**
     * Closes the input reader.
     *
     * @throws java.io.IOException if the reader could not be closed.
     */
    public final void yyclose() throws java.io.IOException {
        zzAtEOF = true; // indicate end of file
        zzEndRead = zzStartRead; // invalidate buffer

        if (zzReader != null) {
            zzReader.close();
        }
    }

    /**
     * Resets the scanner to read from a new input stream.
     *
     * <p>
     * Does not close the old reader.
     *
     * <p>
     * All internal variables are reset, the old input stream <b>cannot</b> be
     * reused (internal buffer is discarded and lost). Lexical state is set to
     * {@code ZZ_INITIAL}.
     *
     * <p>
     * Internal scan buffer is resized down to its initial length, if it has
     * grown.
     *
     * @param reader The new input stream.
     */
    public final void yyreset(java.io.Reader reader) {
        zzReader = reader;
        zzEOFDone = false;
        yyResetPosition();
        zzLexicalState = YYINITIAL;
        if (zzBuffer.length > ZZ_BUFFERSIZE) {
            zzBuffer = new char[ZZ_BUFFERSIZE];
        }
    }

    /**
     * Resets the input position.
     */
    private final void yyResetPosition() {
        zzAtBOL = true;
        zzAtEOF = false;
        zzCurrentPos = 0;
        zzMarkedPos = 0;
        zzStartRead = 0;
        zzEndRead = 0;
        zzFinalHighSurrogate = 0;
        yyline = 0;
        yycolumn = 0;
        yychar = 0L;
    }

    /**
     * Returns whether the scanner has reached the end of the reader it reads
     * from.
     *
     * @return whether the scanner has reached EOF.
     */
    public final boolean yyatEOF() {
        return zzAtEOF;
    }

    /**
     * Returns the current lexical state.
     *
     * @return the current lexical state.
     */
    public final int yystate() {
        return zzLexicalState;
    }

    /**
     * Enters a new lexical state.
     *
     * @param newState the new lexical state
     */
    public final void yybegin(int newState) {
        zzLexicalState = newState;
    }

    /**
     * Returns the text matched by the current regular expression.
     *
     * @return the matched text.
     */
    public final String yytext() {
        return new String(zzBuffer, zzStartRead, zzMarkedPos - zzStartRead);
    }

    /**
     * Returns the character at the given position from the matched text.
     *
     * <p>
     * It is equivalent to {@code yytext().charAt(pos)}, but faster.
     *
     * @param position the position of the character to fetch. A value from 0 to
     * {@code yylength()-1}.
     *
     * @return the character at {@code position}.
     */
    public final char yycharat(int position) {
        return zzBuffer[zzStartRead + position];
    }

    /**
     * How many characters were matched.
     *
     * @return the length of the matched text region.
     */
    public final int yylength() {
        return zzMarkedPos - zzStartRead;
    }

    /**
     * Reports an error that occurred while scanning.
     *
     * <p>
     * In a well-formed scanner (no or only correct usage of
     * {@code yypushback(int)} and a match-all fallback rule) this method will
     * only be called with things that "Can't Possibly Happen".
     *
     * <p>
     * If this method is called, something is seriously wrong (e.g. a JFlex bug
     * producing a faulty scanner etc.).
     *
     * <p>
     * Usual syntax/scanner level error handling should be done in error
     * fallback rules.
     *
     * @param errorCode the code of the error message to display.
     */
    private static void zzScanError(int errorCode) {
        String message;
        try {
            message = ZZ_ERROR_MSG[errorCode];
        } catch (ArrayIndexOutOfBoundsException e) {
            message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
        }

        throw new Error(message);
    }

    /**
     * Pushes the specified amount of characters back into the input stream.
     *
     * <p>
     * They will be read again by then next call of the scanning method.
     *
     * @param number the number of characters to be read again. This number must
     * not be greater than {@link #yylength()}.
     */
    public void yypushback(int number) {
        if (number > yylength()) {
            zzScanError(ZZ_PUSHBACK_2BIG);
        }

        zzMarkedPos -= number;
    }

    /**
     * Contains user EOF-code, which will be executed exactly once, when the end
     * of file is reached
     */
    private void zzDoEOF() throws java.io.IOException {
        if (!zzEOFDone) {
            zzEOFDone = true;

            yyclose();
        }
    }

    /**
     * Resumes scanning until the next regular expression is matched, the end of
     * input is encountered or an I/O-Error occurs.
     *
     * @return the next token.
     * @exception java.io.IOException if any I/O-Error occurs.
     */
    @Override
    public java_cup.runtime.Symbol next_token() throws java.io.IOException {
        int zzInput;
        int zzAction;

        // cached fields:
        int zzCurrentPosL;
        int zzMarkedPosL;
        int zzEndReadL = zzEndRead;
        char[] zzBufferL = zzBuffer;

        int[] zzTransL = ZZ_TRANS;
        int[] zzRowMapL = ZZ_ROWMAP;
        int[] zzAttrL = ZZ_ATTRIBUTE;

        while (true) {
            zzMarkedPosL = zzMarkedPos;

            yychar += zzMarkedPosL - zzStartRead;

            boolean zzR = false;
            int zzCh;
            int zzCharCount;
            for (zzCurrentPosL = zzStartRead;
                    zzCurrentPosL < zzMarkedPosL;
                    zzCurrentPosL += zzCharCount) {
                zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
                zzCharCount = Character.charCount(zzCh);
                switch (zzCh) {
                    case '\u000B':  // fall through
                    case '\u000C':  // fall through
                    case '\u0085':  // fall through
                    case '\u2028':  // fall through
                    case '\u2029':
                        yyline++;
                        yycolumn = 0;
                        zzR = false;
                        break;
                    case '\r':
                        yyline++;
                        yycolumn = 0;
                        zzR = true;
                        break;
                    case '\n':
                        if (zzR) {
                            zzR = false;
                        } else {
                            yyline++;
                            yycolumn = 0;
                        }
                        break;
                    default:
                        zzR = false;
                        yycolumn += zzCharCount;
                }
            }

            if (zzR) {
                // peek one character ahead if it is
                // (if we have counted one line too much)
                boolean zzPeek;
                if (zzMarkedPosL < zzEndReadL) {
                    zzPeek = zzBufferL[zzMarkedPosL] == '\n';
                } else if (zzAtEOF) {
                    zzPeek = false;
                } else {
                    boolean eof = zzRefill();
                    zzEndReadL = zzEndRead;
                    zzMarkedPosL = zzMarkedPos;
                    zzBufferL = zzBuffer;
                    if (eof) {
                        zzPeek = false;
                    } else {
                        zzPeek = zzBufferL[zzMarkedPosL] == '\n';
                    }
                }
                if (zzPeek) {
                    yyline--;
                }
            }
            zzAction = -1;

            zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

            zzState = ZZ_LEXSTATE[zzLexicalState];

            // set up zzAction for empty match case:
            int zzAttributes = zzAttrL[zzState];
            if ((zzAttributes & 1) == 1) {
                zzAction = zzState;
            }

            zzForAction:
            {
                while (true) {

                    if (zzCurrentPosL < zzEndReadL) {
                        zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
                        zzCurrentPosL += Character.charCount(zzInput);
                    } else if (zzAtEOF) {
                        zzInput = YYEOF;
                        break zzForAction;
                    } else {
                        // store back cached positions
                        zzCurrentPos = zzCurrentPosL;
                        zzMarkedPos = zzMarkedPosL;
                        boolean eof = zzRefill();
                        // get translated positions and possibly new buffer
                        zzCurrentPosL = zzCurrentPos;
                        zzMarkedPosL = zzMarkedPos;
                        zzBufferL = zzBuffer;
                        zzEndReadL = zzEndRead;
                        if (eof) {
                            zzInput = YYEOF;
                            break zzForAction;
                        } else {
                            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
                            zzCurrentPosL += Character.charCount(zzInput);
                        }
                    }
                    int zzNext = zzTransL[zzRowMapL[zzState] + zzCMap(zzInput)];
                    if (zzNext == -1) {
                        break zzForAction;
                    }
                    zzState = zzNext;

                    zzAttributes = zzAttrL[zzState];
                    if ((zzAttributes & 1) == 1) {
                        zzAction = zzState;
                        zzMarkedPosL = zzCurrentPosL;
                        if ((zzAttributes & 8) == 8) {
                            break zzForAction;
                        }
                    }

                }
            }

            // store back cached position
            zzMarkedPos = zzMarkedPosL;

            if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
                zzAtEOF = true;
                zzDoEOF();
                {
                    if (indentados == 0) {
                        return new java_cup.runtime.Symbol(sym.EOF);
                    } else {
                        Symbol retorno = indent(yytext(), false, true);
                        if (retorno != null) {
                            return retorno;
                        }
                    }
                }
            } else {
                switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
                    case 1: {
                        Symbol retorno = indent(yytext(), true, false);
                        if (retorno != null) {
                            return retorno;
                        };
                    }
                    // fall through
                    case 97:
                        break;
                    case 2: {
                        return new Symbol(sym.ERRORLEX, yycolumn, yyline, yytext());
                    }
                    // fall through
                    case 98:
                        break;
                    case 3: {
                        yybegin(SALTO);
                    }
                    // fall through
                    case 99:
                        break;
                    case 4: {
                        /*Ignore*/
                    }
                    // fall through
                    case 100:
                        break;
                    case 5: {
                        /*ignore*/
                    }
                    // fall through
                    case 101:
                        break;
                    case 6: {
                        return symbol(sym.NOT);
                    }
                    // fall through
                    case 102:
                        break;
                    case 7: {
                        yybegin(STRING);
                    }
                    // fall through
                    case 103:
                        break;
                    case 8: {
                        return symbol(sym.MOD);
                    }
                    // fall through
                    case 104:
                        break;
                    case 9: {
                        yybegin(CHAR);
                    }
                    // fall through
                    case 105:
                        break;
                    case 10: {
                        return symbol(sym.PAR_A);
                    }
                    // fall through
                    case 106:
                        break;
                    case 11: {
                        return symbol(sym.PAR_C);
                    }
                    // fall through
                    case 107:
                        break;
                    case 12: {
                        return symbol(sym.POR);
                    }
                    // fall through
                    case 108:
                        break;
                    case 13: {
                        return symbol(sym.SUMA);
                    }
                    // fall through
                    case 109:
                        break;
                    case 14: {
                        return symbol(sym.COMA);
                    }
                    // fall through
                    case 110:
                        break;
                    case 15: {
                        return symbol(sym.RESTA);
                    }
                    // fall through
                    case 111:
                        break;
                    case 16: {
                        return symbol(sym.ENTRE);
                    }
                    // fall through
                    case 112:
                        break;
                    case 17: {
                        return symbol(sym.NUMERO);
                    }
                    // fall through
                    case 113:
                        break;
                    case 18: {
                        return symbol(sym.DOS_P);
                    }
                    // fall through
                    case 114:
                        break;
                    case 19: {
                        return symbol(sym.MENOR);
                    }
                    // fall through
                    case 115:
                        break;
                    case 20: {
                        return symbol(sym.ASIGNAR);
                    }
                    // fall through
                    case 116:
                        break;
                    case 21: {
                        return symbol(sym.MAYOR);
                    }
                    // fall through
                    case 117:
                        break;
                    case 22: {
                        return symbol(sym.ID);
                    }
                    // fall through
                    case 118:
                        break;
                    case 23: {
                        return symbol(sym.COR_A);
                    }
                    // fall through
                    case 119:
                        break;
                    case 24: {
                        return symbol(sym.COR_C);
                    }
                    // fall through
                    case 120:
                        break;
                    case 25: {
                        return symbol(sym.POT);
                    }
                    // fall through
                    case 121:
                        break;
                    case 26: {
                        return symbol(sym.LLAVE_A);
                    }
                    // fall through
                    case 122:
                        break;
                    case 27: {
                        return symbol(sym.LLAVE_C);
                    }
                    // fall through
                    case 123:
                        break;
                    case 28: {
                        string.append(yytext());
                    }
                    // fall through
                    case 124:
                        break;
                    case 29: {
                        yybegin(YYINITIAL);
                        return symbol(sym.STRING,
                                string.toString());
                    }
                    // fall through
                    case 125:
                        break;
                    case 30: {
                        return symbol(sym.STRING);
                    }
                    // fall through
                    case 126:
                        break;
                    case 31: {
                        return symbol(sym.CARACTER);
                    }
                    // fall through
                    case 127:
                        break;
                    case 32: {
                        yybegin(YYINITIAL);
                    }
                    // fall through
                    case 128:
                        break;
                    case 33: {
                    }
                    // fall through
                    case 129:
                        break;
                    case 34: {
                        Symbol retorno = indent(yytext(), false, false);
                        if (retorno != null) {
                            return retorno;
                        };
                    }
                    // fall through
                    case 130:
                        break;
                    case 35: {
                        return symbol(sym.NULO);
                    }
                    // fall through
                    case 131:
                        break;
                    case 36: {
                        return symbol(sym.DIFF);
                    }
                    // fall through
                    case 132:
                        break;
                    case 37: {
                        return symbol(sym.AND);
                    }
                    // fall through
                    case 133:
                        break;
                    case 38: {
                        return symbol(sym.XOR);
                    }
                    // fall through
                    case 134:
                        break;
                    case 39: {
                        return symbol(sym.INC);
                    }
                    // fall through
                    case 135:
                        break;
                    case 40: {
                        return symbol(sym.SUMA_S);
                    }
                    // fall through
                    case 136:
                        break;
                    case 41: {
                        return symbol(sym.DEC);
                    }
                    // fall through
                    case 137:
                        break;
                    case 42: {
                        yybegin(COMMENT_M);
                    }
                    // fall through
                    case 138:
                        break;
                    case 43: {
                        yybegin(COMMENT_L);
                    }
                    // fall through
                    case 139:
                        break;
                    case 44: {
                        return symbol(sym.MENOR_I);
                    }
                    // fall through
                    case 140:
                        break;
                    case 45: {
                        return symbol(sym.IGUAL);
                    }
                    // fall through
                    case 141:
                        break;
                    case 46: {
                        return symbol(sym.MAYOR_I);
                    }
                    // fall through
                    case 142:
                        break;
                    case 47: {
                        return symbol(sym.SI);
                    }
                    // fall through
                    case 143:
                        break;
                    case 48: {
                        return symbol(sym.NOTAS);
                    }
                    // fall through
                    case 144:
                        break;
                    case 49: {
                        return symbol(sym.OR);
                    }
                    // fall through
                    case 145:
                        break;
                    case 50: {
                        string.append('\"');
                    }
                    // fall through
                    case 146:
                        break;
                    case 51: {
                        string.append('#');
                    }
                    // fall through
                    case 147:
                        break;
                    case 52: {
                        string.append('\\');
                    }
                    // fall through
                    case 148:
                        break;
                    case 53: {
                        string.append('\n');
                    }
                    // fall through
                    case 149:
                        break;
                    case 54: {
                        string.append('\r');
                    }
                    // fall through
                    case 150:
                        break;
                    case 55: {
                        string.append('\t');
                    }
                    // fall through
                    case 151:
                        break;
                    case 56: {
                        return symbol(sym.CARACTER, "#");
                    }
                    // fall through
                    case 152:
                        break;
                    case 57: {
                        return symbol(sym.CARACTER, "'");
                    }
                    // fall through
                    case 153:
                        break;
                    case 58: {
                        return symbol(sym.CARACTER, "\\");
                    }
                    // fall through
                    case 154:
                        break;
                    case 59: {
                        return symbol(sym.CARACTER, "\n");
                    }
                    // fall through
                    case 155:
                        break;
                    case 60: {
                        return symbol(sym.CARACTER, "\r");
                    }
                    // fall through
                    case 156:
                        break;
                    case 61: {
                        return symbol(sym.CARACTER, "\t");
                    }
                    // fall through
                    case 157:
                        break;
                    case 62: {
                        return symbol(sym.NAND);
                    }
                    // fall through
                    case 158:
                        break;
                    case 63: {
                        return symbol(sym.NOR);
                    }
                    // fall through
                    case 159:
                        break;
                    case 64: {
                        return symbol(sym.NUMERO_D);
                    }
                    // fall through
                    case 160:
                        break;
                    case 65: {
                        return symbol(sym.VAR);
                    }
                    // fall through
                    case 161:
                        break;
                    case 66: {
                        return symbol(sym.CASO);
                    }
                    // fall through
                    case 162:
                        break;
                    case 67: {
                        return symbol(sym.KEEP);
                    }
                    // fall through
                    case 163:
                        break;
                    case 68: {
                        return symbol(sym.PARA);
                    }
                    // fall through
                    case 164:
                        break;
                    case 69: {
                        return symbol(sym.SINO);
                    }
                    // fall through
                    case 165:
                        break;
                    case 70: {
                        return symbol(sym.TRUE);
                    }
                    // fall through
                    case 166:
                        break;
                    case 71: {
                        return symbol(sym.DECIMAL);
                    }
                    // fall through
                    case 167:
                        break;
                    case 72: {
                        return symbol(sym.FALSE);
                    }
                    // fall through
                    case 168:
                        break;
                    case 73: {
                        return symbol(sym.HACER);
                    }
                    // fall through
                    case 169:
                        break;
                    case 74: {
                        return symbol(sym.PAR);
                    }
                    // fall through
                    case 170:
                        break;
                    case 75: {
                        return symbol(sym.PISTA);
                    }
                    // fall through
                    case 171:
                        break;
                    case 76: {
                        return symbol(sym.SALIR);
                    }
                    // fall through
                    case 172:
                        break;
                    case 77: {
                        return symbol(sym.CADENA);
                    }
                    // fall through
                    case 173:
                        break;
                    case 78: {
                        return symbol(sym.ENTERO);
                    }
                    // fall through
                    case 174:
                        break;
                    case 79: {
                        return symbol(sym.SWITCH);
                    }
                    // fall through
                    case 175:
                        break;
                    case 80: {
                        return symbol(sym.BOOLEAN);
                    }
                    // fall through
                    case 176:
                        break;
                    case 81: {
                        return symbol(sym.DEFAULT);
                    }
                    // fall through
                    case 177:
                        break;
                    case 82: {
                        return symbol(sym.ESPERAR);
                    }
                    // fall through
                    case 178:
                        break;
                    case 83: {
                        return symbol(sym.IMPAR);
                    }
                    // fall through
                    case 179:
                        break;
                    case 84: {
                        return symbol(sym.MSG);
                    }
                    // fall through
                    case 180:
                        break;
                    case 85: {
                        return symbol(sym.ORDENAR);
                    }
                    // fall through
                    case 181:
                        break;
                    case 86: {
                        return symbol(sym.RETORNA);
                    }
                    // fall through
                    case 182:
                        break;
                    case 87: {
                        return symbol(sym.CHAR);
                    }
                    // fall through
                    case 183:
                        break;
                    case 88: {
                        return symbol(sym.EXT);
                    }
                    // fall through
                    case 184:
                        break;
                    case 89: {
                        return symbol(sym.LONG);
                    }
                    // fall through
                    case 185:
                        break;
                    case 90: {
                        return symbol(sym.MIENTRAS);
                    }
                    // fall through
                    case 186:
                        break;
                    case 91: {
                        return symbol(sym.CONT);
                    }
                    // fall through
                    case 187:
                        break;
                    case 92: {
                        return symbol(sym.PRINCIPAL);
                    }
                    // fall through
                    case 188:
                        break;
                    case 93: {
                        return symbol(sym.SUMARIZAR);
                    }
                    // fall through
                    case 189:
                        break;
                    case 94: {
                        return symbol(sym.ASC);
                    }
                    // fall through
                    case 190:
                        break;
                    case 95: {
                        return symbol(sym.REPRODUCIR);
                    }
                    // fall through
                    case 191:
                        break;
                    case 96: {
                        return symbol(sym.DESC);
                    }
                    // fall through
                    case 192:
                        break;
                    default:
                        zzScanError(ZZ_NO_MATCH);
                }
            }
        }
    }

}
