
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SUMA_S = 58;
  public static final int MENOR_I = 42;
  public static final int COR_C = 60;
  public static final int COR_A = 59;
  public static final int EXT = 3;
  public static final int ASC = 28;
  public static final int MAYOR = 39;
  public static final int NUMERO_D = 73;
  public static final int SI = 13;
  public static final int INDENT = 76;
  public static final int CONT = 18;
  public static final int KEEP = 11;
  public static final int DEDENT = 77;
  public static final int POT = 55;
  public static final int PRIMOS = 32;
  public static final int POR = 52;
  public static final int NUMERO = 72;
  public static final int PISTA = 2;
  public static final int PAR_C = 71;
  public static final int FALSE = 10;
  public static final int PAR_A = 70;
  public static final int NOT = 49;
  public static final int NOR = 48;
  public static final int ORDENAR = 27;
  public static final int DEC = 56;
  public static final int VAR = 12;
  public static final int MAYOR_I = 41;
  public static final int LLAVE_C = 64;
  public static final int LLAVE_A = 63;
  public static final int SALIR = 17;
  public static final int HACER = 22;
  public static final int PARA = 20;
  public static final int MOD = 54;
  public static final int COMA = 62;
  public static final int SAL = 65;
  public static final int ENTERO = 4;
  public static final int TRUE = 9;
  public static final int LONG = 34;
  public static final int IGUAL = 37;
  public static final int PAR = 30;
  public static final int DECIMAL = 5;
  public static final int CHAR = 7;
  public static final int BOOLEAN = 6;
  public static final int ERRORLEX = 75;
  public static final int SWITCH = 15;
  public static final int MENOR = 40;
  public static final int NULO = 43;
  public static final int ARREGLO = 66;
  public static final int EOF = 0;
  public static final int MIENTRAS = 21;
  public static final int PUNTOC = 79;
  public static final int DEFAULT = 19;
  public static final int SUMA = 50;
  public static final int SUMARIZAR = 33;
  public static final int INC = 57;
  public static final int CARACTER = 69;
  public static final int ENTRE = 53;
  public static final int PRINCIPAL = 36;
  public static final int MSG = 35;
  public static final int NOTAS = 25;
  public static final int OR = 46;
  public static final int error = 1;
  public static final int REPRODUCIR = 24;
  public static final int DIFF = 38;
  public static final int IMPAR = 31;
  public static final int RESTA = 51;
  public static final int DESC = 29;
  public static final int ID = 67;
  public static final int DOS_P = 61;
  public static final int SINO = 14;
  public static final int CASO = 16;
  public static final int ESPERAR = 26;
  public static final int RETORNA = 23;
  public static final int CADENA = 8;
  public static final int STRING = 68;
  public static final int AND = 44;
  public static final int UMINUS = 78;
  public static final int ASIGNAR = 74;
  public static final int NAND = 45;
  public static final int XOR = 47;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PISTA",
  "EXT",
  "ENTERO",
  "DECIMAL",
  "BOOLEAN",
  "CHAR",
  "CADENA",
  "TRUE",
  "FALSE",
  "KEEP",
  "VAR",
  "SI",
  "SINO",
  "SWITCH",
  "CASO",
  "SALIR",
  "CONT",
  "DEFAULT",
  "PARA",
  "MIENTRAS",
  "HACER",
  "RETORNA",
  "REPRODUCIR",
  "NOTAS",
  "ESPERAR",
  "ORDENAR",
  "ASC",
  "DESC",
  "PAR",
  "IMPAR",
  "PRIMOS",
  "SUMARIZAR",
  "LONG",
  "MSG",
  "PRINCIPAL",
  "IGUAL",
  "DIFF",
  "MAYOR",
  "MENOR",
  "MAYOR_I",
  "MENOR_I",
  "NULO",
  "AND",
  "NAND",
  "OR",
  "XOR",
  "NOR",
  "NOT",
  "SUMA",
  "RESTA",
  "POR",
  "ENTRE",
  "MOD",
  "POT",
  "DEC",
  "INC",
  "SUMA_S",
  "COR_A",
  "COR_C",
  "DOS_P",
  "COMA",
  "LLAVE_A",
  "LLAVE_C",
  "SAL",
  "ARREGLO",
  "ID",
  "STRING",
  "CARACTER",
  "PAR_A",
  "PAR_C",
  "NUMERO",
  "NUMERO_D",
  "ASIGNAR",
  "ERRORLEX",
  "INDENT",
  "DEDENT",
  "UMINUS",
  "PUNTOC"
  };
}

