
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizador;

/** CUP generated class containing symbol constants. */
public class symLista {
  /* terminals */
  public static final int DOS_P = 13;
  public static final int TRUE = 8;
  public static final int COR_C = 11;
  public static final int DOSP = 7;
  public static final int ID = 16;
  public static final int COR_A = 10;
  public static final int STRING = 17;
  public static final int RANDOM = 4;
  public static final int COMA = 12;
  public static final int NOMBRE = 3;
  public static final int EOF = 0;
  public static final int CIRCULAR = 5;
  public static final int FALSE = 9;
  public static final int error = 1;
  public static final int LLAVE_C = 15;
  public static final int LLAVE_A = 14;
  public static final int PISTAS = 6;
  public static final int LISTA = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LISTA",
  "NOMBRE",
  "RANDOM",
  "CIRCULAR",
  "PISTAS",
  "DOSP",
  "TRUE",
  "FALSE",
  "COR_A",
  "COR_C",
  "COMA",
  "DOS_P",
  "LLAVE_A",
  "LLAVE_C",
  "ID",
  "STRING"
  };
}

