
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizador;

/** CUP generated class containing symbol constants. */
public class symSolicitud {
  /* terminals */
  public static final int SIN = 21;
  public static final int DURACION = 10;
  public static final int ERRORLEX = 19;
  public static final int OCTAVA = 11;
  public static final int DATOS = 7;
  public static final int PISTA = 5;
  public static final int ID = 18;
  public static final int TIPO = 3;
  public static final int STRING = 17;
  public static final int NOTA = 9;
  public static final int NOMBRE = 20;
  public static final int EOF = 0;
  public static final int CANAL = 8;
  public static final int MENOR_Q = 14;
  public static final int error = 1;
  public static final int NOTAS = 12;
  public static final int NUMERO = 13;
  public static final int LISTA = 4;
  public static final int FIN = 16;
  public static final int SOLICITUD = 2;
  public static final int MAYOR_Q = 15;
  public static final int PISTANUEVA = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SOLICITUD",
  "TIPO",
  "LISTA",
  "PISTA",
  "PISTANUEVA",
  "DATOS",
  "CANAL",
  "NOTA",
  "DURACION",
  "OCTAVA",
  "NOTAS",
  "NUMERO",
  "MENOR_Q",
  "MAYOR_Q",
  "FIN",
  "STRING",
  "ID",
  "ERRORLEX",
  "NOMBRE",
  "SIN"
  };
}

